### PR TITLE
Centring a button

### PR DESCRIPTION
**Pull request by Somespi**
I have did some few changes , which are:

1. adding hover & click effects. 
2. Centring the button by deviding the current screen width by 2

### CODE REVIEW

**Comment by YhyaGithub** [comment]
I think we don't need any animations for now but,
Make Animation That When You Click The Background Turn Into Completely White and The Text Is Transparent

**Comment by YhyaGithub** [comment]
@Somespi

**Comment by Somespi** [comment]
Done

**Review by YhyaGithub — APPROVED** [review]
Approved

**Pull request merged**
